# Generated by Django 6.0.3 on 2026-04-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('amman', 'Amman'), ('zarqa', 'Zarqa'), ('irbid', 'Irbid'), ('aqaba', 'Aqaba'), ('madaba', 'Madaba'), ('karak', 'Karak'), ('mafraq', 'Mafraq'), ('ajloun', 'Ajloun'), ('balqa', 'Balqa'), ('maan', 'Maan'), ('jerash', 'Jerash')], max_length=20),
        ),
    ]
